# Setup
title: Andrew Alieksieiev
description: Enthusiastic personal blog
url: https://github.com/Brainisthekey
avatar: /assets/img/avatar.jpeg
permalink: pretty
cover_image: /assets/img/background.jpeg
about-img: /assets/img/profile-img.jpeg

collections:
  posts:
    output: true
  activity:
    output: true


# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec


twitter:
  username: Brain_keyy
  card: summary
logo: logo.png
social:
  name: Andrew Alieksieiev
  links:
    - https://twitter.com/Brain_keyy
    - https://github.com/Brainisthekey
google_site_verification: xxxxx
lang: en


sass:
  sass_dir: _sass
  style: :compressed


author:
  name: Andrew Alieksieiev
  url: https://github.com/Brainisthekey
  email: andriialieksieiev@gmail.com
