# Setup
title: Andrew Alieksieiev
description: Enthusiastic personal blog
url: https://github.com/Brainisthekey
baseurl: "/brainkey_blog"

# Photos
avatar: /assets/img/avatar.jpeg
cover_image: /assets/img/background.jpeg
wrocpy: /assets/img/wrocpy.jpg
pytech: /assets/img/pytech.png
python-katowice: /assets/img/python-katowice.jpg
code-europe-img: /assets/img/code-europe-img.jpeg
game-of-teens: /assets/img/game-of-teens.jpeg

# Videos
code-europe-video: https://www.youtube.com/embed/Sa3wzudPZZo
frontend-for-backend: https://www.youtube.com/embed/pJWJjvRaAM0

permalink: pretty

collections:
  posts:
    output: true
  activity:
    output: true


# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate: 5


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec


twitter:
  username: Brain_keyy
  card: summary
logo: logo.png
social:
  name: Andrew Alieksieiev
  links:
    - https://twitter.com/Brain_keyy
    - https://github.com/Brainisthekey
google_site_verification: xxxxx
lang: en


sass:
  sass_dir: _sass
  style: :compressed


author:
  name: Andrew Alieksieiev
  url: https://github.com/Brainisthekey
  email: andriialieksieiev@gmail.com
